config/routes.rb
Rails.application.routes.draw do
  controller :admin do
    get 'admin' => 'admin#index'
  end
  
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  get 'store/index'
  root 'store#index'
  get 'store/index' => 'store#index', as: :store
  get 'line_items/quantity_decrement/:id' => 'line_items#quantity_decrement', as: :decrement
  resources :products do
    get :who_bought, on: :member
  end

  resources :products

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
#  before_create :assign_price
  
  def total_price
    product.price * quantity
  end
  
  def assign_price
    self.price = product.price
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create, :decrement] #ActiveRecord callback
  before_action :set_line_item, only: [:show, :edit, :update, :destroy] #ActiveRecord callback
 skip_before_action :authorize, only: :create
  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end
  def quantity_decrement
    @line_item = LineItem.find(params[:id])
    @cart = Cart.find(@line_item.cart_id)
    @cart.decrement_quantity(@line_item.product_id)


    respond_to do |format|
        format.html { redirect_to root_url}
        format.js{@current_item = @line_item}
        format.json { render :show, status: :created, location: @line_item }
    end
  end

  # POST /line_items
  # POST /line_items.json
  def create
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id, product.price)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_url}
        format.js {@current_item = @line_item}
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json

  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, 
                    notice: 'Line item was successfully destroyed.' 
      }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:product_id)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br>
    <%= f.text_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if line_item == @current_item %>
  <tr id="current_item">
<% else %>
  <tr>
<% end %>
  <td>
    <%=link_to "put back", decrement_path(line_item), remote: true%>
  </td>
  <td>
    <%= line_item.quantity%> 
  </td>
  <td>
   <%= line_item.product.title %>
  </td>
  <td class="item_price">
    <%= number_to_currency(line_item.total_price) %> 
  </td>
  <td>
    <%=link_to "Delete item", 
      line_item, method: :delete,
      data:{confirm: "Are you sure"}%>
  </td>
</tr>

app/views/line_items/_line_item.text.erb
<%= sprintf("%2d x %s",
  line_item.quantity,
  truncate(line_item.product.title, length: 50))
 %>

app/views/line_items/create.js.erb
$('#notice').hide();

if ($('#cart tr').length ==1) { $('#cart').show('blind', 1000); }

$('#cart').html("<%= escape_javascript render(@cart) %>");


$('#current_item').css({'background-color': '#88ff88'}).animate({'background-color': '#114411'}, 1000);

app/views/line_items/debub.html.erb
<%= @item.inspect %>
<%= @cart.inspect %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Line Items</h1>

  <table>
    <thead>
      <tr>
        <th>Product</th>
        <th>Cart</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @line_items.each do |line_item| %>
        <tr>
          <td><%= line_item.product %></td>
          <td><%= line_item.cart %></td>
          <td><%= link_to 'Show', line_item %></td>
          <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
          <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/line_item.text.erb
<%= sprintf("%2d x %s",
  line_item.quantity,
  truncate(line_item.product.title, length: 50))
 %>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/quantity_decrement.js.erb
$('#cart').html("<%= escape_javascript render(@cart) %>");
$('#current_item').css({'background-color': '#88ff88'}).animate({'background-color': '#114411'}, 1000);

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line_item.product %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @line_item.cart %>
</p>

<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>